### ISSUE TITLE
Ability to set an arbitrary ownCloud URL

### ISSUE THREAD

**Issue by PVince81** [owncloud/file-picker#17]
- As a web app developer, I want my users to be able to save data in their own ownCloud instances, so that they remain in control of their data and I do not need to provide storage for these users.

- As a user of a given web app, I want to save my data/files into my ownCloud, so that they remain in my control.
(similar to "save to Dropbox")

Currently the web app developer must specify a static ownCloud URL in the config file, so it implies that there is an existing instance that is designed to be used with that web app.

These user stories imply more than just being able to select a target folder. It would require the webapp backend to also have a way to keep connected to the ownCloud instance and access the data there.

@LukasHirt @pmaier1

**Comment by LukasHirt** [comment]
I am thinking in this case how the authorisation would be handled. Would it then be something like with iOS and android - there would be predefined endpoints which could be used?

**Comment by LukasHirt** [comment]
OIDC js client will be removed and we'll be relying solely on getting bearer token via prop. This feature is not going to be possible with this approach.

**Comment by pmaier1** [comment]
> OIDC js client will be removed and we'll be relying solely on getting bearer token via prop. 

Does is make sense to keep both approaches?
a) File picker can do its own authentication
b) File picker can receive tokens from 3rd party

I think there are use cases for both (not necessarily the one requested in this ticket).

**Comment by LukasHirt** [comment]
@pmaier1 It would be possible. I just understood from our last call that wouldn't be the goal. We can simply pass a check - if the bearer token is not provided, fall back to authorisation.

**Comment by pmaier1** [comment]
I like that idea. While it's currently not necessary to specify arbitrary oC URLs, it might still be needed to have a dedicated authentication for the file picker.
