### ISSUE TITLE
Initial focus not working

### ISSUE THREAD

**Issue by kulmann** [owncloud/file-picker#59]
Apparently the initial focus doesn't work:

This does not work when wrapped in a web component. According to [the source](https://github.com/vuejs/vue-web-component-wrapper/blob/f4c06998ac20585cba7e9b0a5836902e2aa2a50a/src/index.js#L162), `mounted()` is called *before* the element is added to the DOM. A `focus()` does nothing at that point.

Also, if the primary use case of the file picker is a widget, then it should not steal the focus on its own. Instead, the web component should properly handle `focus()` calls from outside. This would allow the container to decide whether and when the file picker gets the focus.

Handling `focus()` calls is required anyway to allow proper focus-trapping when used in a modal dialog: Since the dialog might contain other elements, the file picker can't trap the focus only inside itself. So the container has to do it. And since the file picker is typically the first element, then it will need to handle external calls to `focus()` by forwarding them to the first focusable element inside itself.

_Originally posted by @VP- in https://github.com/owncloud/file-picker/issues/44#issuecomment-832610871_

**Comment by LukasHirt** [comment]
Initial focused has been removed and is left to be taken care of by the consumer

**Comment by VP-** [comment]
Focusing from outside does not work, since the selector from the example (`#oc-checkbox-3`) does not exist until the list of files is downloaded from the server. The consumer currently has no way to know when that happens.

Also, the selector itself is non-deterministic because the number at the end keeps increasing, and will be not present anymore e.g. after the user switched folders.

**Comment by LukasHirt** [comment]
The checkbox selector was used as a pure example of how the selector can look like. For initial focus should be used the file picker component itself so that no content is lost for screenreaders.
