### ISSUE TITLE
Breadcrumb navigation broken

### ISSUE THREAD

**Issue by kulmann** [owncloud/file-picker#64]
The breadcrumb navigation seems to be broken.

## Steps to reproduce
1. Create a folder hierarchy A/B/C/D
2. Navigate into folder D
3. Try to navigate into one of the folders up the hierarchy, let's pick C

## Expected behaviour
Navigation into C is successful and I can see folder contents of C

## Actual behaviour 
- Breadcrumbs stay the same (`Home / A / B / C / D`) although I clicked on `C`
- No folder contents visible. Instead I see a loading spinner.

# browser logs
The JS console shows that the propfind contains an encoded path, thus the propfind fails:
`PROPFIND http://host.docker.internal/px1/remote.php/webdav/A%252FB%252FC 404 (Not Found)`

There is another, probably unrelated, error in the JS console:
```
owncloud.js?4716:1 Uncaught (in promise) TypeError: Cannot read property 'data' of undefined
    at eval (owncloud.js?4716:1)
```

# Screenshot
<img width="2032" alt="Screenshot 2021-06-10 at 14 28 07" src="https://user-images.githubusercontent.com/3532843/121525632-dce50100-c9f8-11eb-8595-47f73c807878.png">

Bonus points for adding tests to avoid this in the future. ;-)

**Comment by VP-** [comment]
In 0.6.0 I get the spinner when clicking on the *current* folder in the breadcrumb.

**Comment by kulmann** [comment]
cc @LukasHirt
