### ISSUE TITLE
File Picker in iframes

### ISSUE THREAD

**Issue by LarsLuz** [owncloud/file-picker#67]
Hi,

we've encountered a problem when using the file picker inside of an iframe.

The problem is that some browsers have started to deny the access to the session storage for third party iframes.
As we are using the file picker in a widget solution for the elements chat client we can't load the widget in some browsers.

The file picker uses the WebStorage Store backend of the oidc-client. Would it be possible to add an option to load the InMemory storage instead?

**Comment by LukasHirt** [comment]
Hi @LarsLuz could you pls fill in a bit more details? I think there could be a chance of getting around this.

1) In what browser (name and version) have you seen this?
2) Could you set in the server where the iframe is included CORS headers to allow the URL that is set as iframe src?

After setting that CORS header I cannot reproduce this in any major browser (safari, ff, chrome). I would like to avoid having to use the memory storage as it's being purged on every refresh so we'd lose the authorised context always which is just bad UX. If you confirm the issue, I have prepared a PR which would use that storage #74 There just needs to be added option to switch between session and memory via config.json. If you could however confirm that the CORS header helps, I'd close that PR and wouldn't introduce extra logic then.

**Comment by LarsLuz** [comment]
Hi @LukasHirt 

the problematic behavior is mainly visible in Chrome. The problem was actually reported by one of your colleagues, at first I couldn't reproduce it on my PC. Apparently some Linux distros already are setting the harsh cookie policies that Google wants to introduce in the future ( https://www.cookiebot.com/en/google-third-party-cookies/ ). I could only reproduce it through denying third party cookies in the Chrome settings. Could you try to do the same?

Currently I'm setting X-Frame-Options: ALLOW-FROM https://app.element.io/
I've also tried adding the following headers:
Access-Control-Allow-Origin: *
Access-Control-Expose-Headers: *
Access-Control-Allow-Credentials: true

Furthermore I've checked the news again, it seems that Google has pushed back the end for third party cookie support to 2023. Therefore I am not sure how we should proceed from here

**Comment by LukasHirt** [comment]
Option to select memory storage has been released now https://github.com/owncloud/file-picker/releases/tag/v0.8.0 I haven't managed to reproduce the issue with that config anymore.

**Comment by LarsLuz** [comment]
Sorry to bother you again. The file picker now seems to access the localStorage at a different place in the code

https://github.com/owncloud/file-picker/blob/e13565f67dda3df422530f701a58334f486cf146/src/services/auth.js#L60

As soon as the UserManager ist initialized I'm getting the error again.

**Comment by kulmann** [comment]
Reopening for investigation

**Comment by LukasHirt** [comment]
@LarsLuz I could not reproduce this anymore. The only case I could was if I disabled **all** cookies, not only third party but that's nothing we should actually care about as it's not default browser settings and is even mentioned in settings that it **will** break websites.

I tried it in FF and chrome. Both worked fine. App running in nodejs server with an iframe that loads file picker from another nodejs server.

**Comment by LarsLuz** [comment]
Uncaught (in promise) DOMException: Failed to read the 'localStorage' property from 'Window': Access is denied for this document.
    at Function.get (https://owncloud-demo.etes.cloud/oc74713/phoenix/js/element-file-picker/element-file-picker.bundle.js:48915:55)
    at new o (https://owncloud-demo.etes.cloud/oc74713/phoenix/js/element-file-picker/element-file-picker.bundle.js:49214:88)
    at C.B (https://owncloud-demo.etes.cloud/oc74713/phoenix/js/element-file-picker/element-file-picker.bundle.js:49060:52)
    at new C (https://owncloud-demo.etes.cloud/oc74713/phoenix/js/element-file-picker/element-file-picker.bundle.js:54881:23)
    at new m (https://owncloud-demo.etes.cloud/oc74713/phoenix/js/element-file-picker/element-file-picker.bundle.js:54564:69)
    at ne (https://owncloud-demo.etes.cloud/oc74713/phoenix/js/element-file-picker/element-file-picker.bundle.js:57503:23)
    at https://owncloud-demo.etes.cloud/oc74713/phoenix/js/element-file-picker/element-file-picker.bundle.js:57992:40
    at l (https://owncloud-demo.etes.cloud/oc74713/phoenix/js/element-file-picker/element-file-picker.bundle.js:36141:46)
    at Generator.e._invoke (https://owncloud-demo.etes.cloud/oc74713/phoenix/js/element-file-picker/element-file-picker.bundle.js:36129:21)
    at Generator.next (https://owncloud-demo.etes.cloud/oc74713/phoenix/js/element-file-picker/element-file-picker.bundle.js:36170:29)

**Comment by LukasHirt** [comment]
@LarsLuz Yep, I was testing it later in the day directly in elements by adding the widget and saw the same. I have a PR here #78 which might be able to fix it but first need to merge and release it and then we can test it again by updating it in the element widget

**Comment by LukasHirt** [comment]
@LarsLuz new version has been released now. Could you pls update it on the demo instance so that we can try out if it will finally fix the issue?

**Comment by LarsLuz** [comment]
@LukasHirt Thanks, it works now!
